package com.example.jpastart.controller;

import com.example.jpastart.model.Student;
import com.example.jpastart.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.util.List;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/students")
    public List<Student> students (){
        List<Student> list = studentRepository.findAll();
        return list;
    }

    @GetMapping("/addStudent")
    public List<Student> addStudent (){
        Student std = new Student();
        std.setBorn(LocalDate.now());
        std.setBornTime(LocalDate.now());

        List<Student> list = studentRepository.findAll();

        std.setName("AutoGenerated size "+  list.size());
        studentRepository.save(std);
        return list;
    }
}
